trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: 'clamav-http-poc'
  containerRegistry: 'my-acr-service-connection'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build and push image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(containerRegistry)
    tags: |
      $(tag)
      latest